CPMAddPackage(
  NAME SoapySDR
  GITHUB_REPOSITORY pothosware/SoapySDR
  VERSION 0.8.1
  GIT_TAG soapy-sdr-0.8.1
  OPTIONS
    "BUILD_SHARED_LIBS OFF"
    "ENABLE_DOCS OFF"
    "ENABLE_PYTHON OFF"
    "ENABLE_PYTHON3 OFF"
    "ENABLE_TESTS OFF"
)

set(SOAPY_SDR_ABI_VERSION "0.8")
